BALL_SPEED_DEFAULT = 2
PADDLE_SIZE_DEFAULT = 2
HUMAN_PLAYERS_DEFAULT = 1
ONLINE_PLAYERS_DEFAULT = 0
AI_OPPONENTS_LOCAL_DEFAULT = 0
AI_OPPONENTS_ONLINE_DEFAULT = 0
IS_PRIVATE_DEFAULT = 0


DEFAULT_COLORS = ["#ffffff", "#ffffff", "#000000", "#000000", "#aaaaaa", "#dcdcdc80"]
DEFAULT_SETTINGS = [
    BALL_SPEED_DEFAULT,
    PADDLE_SIZE_DEFAULT,
    HUMAN_PLAYERS_DEFAULT,
    ONLINE_PLAYERS_DEFAULT,
    AI_OPPONENTS_LOCAL_DEFAULT,
    AI_OPPONENTS_ONLINE_DEFAULT,
    IS_PRIVATE_DEFAULT,
]
