BALL_SPEED_OPTIONS = ['snail', 'deer', 'lion', 'hawk', 'jet']
PADDLE_SIZE_OPTIONS = ['tiny', 'small', 'medium', 'large', 'jumbo']
NUMBER_PLAYERS_OPTIONS = ['2', '3', '4']
IS_PRIVATE_OPTIONS = ['public', 'private']

BALL_SPEED_DEFAULT = 2
PADDLE_SIZE_DEFAULT = 2
NUMBER_PLAYERS_DEFAULT = 0
IS_PRIVATE_DEFAULT = 0


DEFAULT_COLORS = ["#ffffff", "#ffffff", "#000000", "#000000", "#aaaaaa", "#dcdcdc80"]
DEFAULT_SETTINGS = [BALL_SPEED_DEFAULT, PADDLE_SIZE_DEFAULT, NUMBER_PLAYERS_DEFAULT, IS_PRIVATE_DEFAULT]
