version: '3'

services:
    db:
        image: db
        container_name: db
        build:
            context: db
        volumes:
            - db:/var/lib/pgsql/data
        expose:
            - "5432:5432"
        networks:
            - transcendence
        restart: unless-stopped
        env_file: .env
        healthcheck:
            test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            interval: 5s
            timeout: 1s
            retries: 20
            start_period: 5s

    back:
        image: back
        container_name: back
        build:
            context: back
        command: ["./wait-for-it.sh", "db", "5432", "python3", "transcendence_django/manage.py", "runserver"]
        depends_on:
            - db
        ports:
            - "8000:8000"
        networks:
            - transcendence
        restart: unless-stopped
        env_file: .env
        # healthcheck:
        #     test: 'curl -kfsSL https://localhost:443/back_status'
        #     interval: 5s
        #     timeout: 1s
        #     retries: 10
        #     start_period: 5s

    front:
        image: front
        container_name: front
        build:
            context: front
        expose:
            - "4200:4200"
        networks:
            - transcendence
        restart: unless-stopped
        # env_file: .env
        depends_on:
            - back
            # db:
            #     condition: service_healthy

volumes:
    db:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '${PWD}/db/data'

networks:
    transcendence:
        name: transcendence
