# AIPI CLIENT CONSTANTS
MAX_CONNECT_ATTEMPTS = 5

CALC_PRECISION = 0.85
DUMB_PRECISION = 0.70

# AIPI VIEW CONSTANTS
API_GAME_SOCKET = "wss://back-game"
API_USER_ENDPOINT = "https://back-user/user/user-data"

UID_RNG_BEGIN = 1000
UID_RNG_END = 10000
UID_RNG_STEP = 1000
