global:
  resolve_timeout: 5m

route:
  receiver: discord_alert

receivers:
- name: discord_alert
  discord_configs:
  - webhook_url: # copy the webhook URL here (make an env var?)
    title: '{{ template "custom_title" . }}'
    message: '{{ template "custom_discord_message" . }}'

templates:
  - '/etc/alertmanager/templates/default.tmpl'
