# Game area dimensions
GAME_WIDTH = 100
GAME_HEIGHT = 100

# Game arena
MIN_PLAYER = 2
MAX_PLAYER = 10

# Ball parameters
BALL_INITIAL_POSITION = {'x': 50, 'y': 50}
BALL_INITIAL_VELOCITY = {'x': 5, 'y': 5}
MAX_VELOCITY = 10
MIN_VELOCITY = 1
BALL_RADIUS = 3
           
# Paddle parameters
PADDLE_INITIAL_POSITION = {'y': 50}
PADDLE_WIDTH = 10
PADDLE_HEIGHT = 50
LEFT = 1
RIGHT = 2
