from transcendence_django.dict_keys import LOCAL, LOSS, REMOTE, TIE, TOTAL, WIN

DEFAULT_TIME_PLAYED = {LOCAL: 0, REMOTE: 0, TOTAL: 0}
DEFAULT_GAME_COUNTER = {LOCAL: 0, REMOTE: 0, TOTAL: 0}
DEFAULT_WIN_LOSS_TIE = {WIN: 0, LOSS: 0, TIE: 0, TOTAL: 0}

TIME_OUT_ONLINE=5