[tool.black]
line_length = 88
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git/
    | \.hg/
    | \.mypy_cache/
    | \.tox/
    | \.venv/
    | build/
    | dist/
  )/
)
'''

[tool.blacken-docs]
target_version = ['py38']
line_length = 120