name: Docker Containers Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create env file
        run: |
          echo POSTGRES_USER="${{ secrets.POSTGRES_USER }}" >> .env
          echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo POSTGRES_DB="${{ secrets.POSTGRES_DB }}" >> .env
          echo PGDATA="$PWD/db/data" >> .env
      - name: Build containers
        run: |
          make
      - name: Check containers status
        run: |
          make health
