name: Docker Containers Check

on:
  pull_request:
    branches:
      - main
      - MVE[0-9]

jobs:
  check-containers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create env file
        run: |
          {
            echo POSTGRES_USER="${{ secrets.POSTGRES_USER }}";
            echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}";
            echo POSTGRES_DB="${{ secrets.POSTGRES_DB }}";
            echo PGDATA="$PWD/db/data";
            echo DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}";
            echo DOCKSOCKUID="$(id -u)";
          } >> .env

      - name: Create discord webhook file for alertmanager
        run: echo "${{ secrets.DISCORD_WEBHOOK }}" > ./monitoring/alertmanager/very-secret-webhook-url

      - name: Install mkcert
        run: |
          sudo apt-get install -y libnss3-tools
          wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
          chmod +x mkcert-v1.4.3-linux-amd64
          mv mkcert-v1.4.3-linux-amd64 /usr/local/bin/mkcert

      - name: Build containers AND check healthiness
        run: |
          make || { make logs; exit 1; }
